# -*- coding: utf-8 -*-
"""CHALLEND 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h4dwcdRNXY6Md7y8oo4JMEeNWGXlENfT
"""

import pandas as pd

banco = pd.read_json('/content/TelecomX_Data.json')

banco

df = pd.DataFrame(banco)
df

df.info()

#TRATANDO INCONSISTENCIAS

import pandas as pd

colunas_dict = ['customer', 'phone', 'internet', 'account']

df_expandido = df.drop(columns=colunas_dict).copy()

for coluna in colunas_dict:
    dados_expandido = pd.json_normalize(df[coluna])

    dados_expandido = dados_expandido.add_prefix(f'{coluna}_')

    df_expandido = pd.concat([df_expandido, dados_expandido], axis=1)

print(df_expandido.head())

df = df_expandido

df

#SeniorCitizen: informação sobre um cliente ter ou não idade igual ou maior que 65 anos
#Partner: se o cliente possui ou não um parceiro ou parceira
#Dependents: se o cliente possui ou não dependentes
#PhoneService: assinatura de serviço telefônico
#MultipleLines: assisnatura de mais de uma linha de telefone
#InternetService: assinatura de um provedor internet
#OnlineSecurity: assinatura adicional de segurança online
#OnlineBackup: assinatura adicional de backup online
#DeviceProtection: assinatura adicional de proteção no dispositivo
#TechSupport: assinatura adicional de suporte técnico, menos tempo de espera
#StreamingTV: assinatura de TV a cabo
#StreamingMovies: assinatura de streaming de filmes
#Contract: tipo de contrato
#PaperlessBilling: se o cliente prefere receber online a fatura
#PaymentMethod: forma de pagamento
##Charges.Total: total gasto pelo cliente

df = df.rename(columns={
    'customer_gender': 'genero',
    'customer_SeniorCitizen': 'idade>=65',
       'customer_Partner': 'conjugue',
     'customer_Dependents': 'dependentes', 'customer_tenure':'meses_contrato',
       'phone_PhoneService':'servico_telefonico', 'phone_MultipleLines': 'multiplas_linhas',
     'internet_InternetService': 'assinatura_provedor','internet_OnlineSecurity': 'seguranca_online',
    'internet_OnlineBackup': 'backup_online',
       'internet_DeviceProtection':'proteção_dispositivo', 'internet_TechSupport': 'suporte_tecnico',
       'internet_StreamingTV': 'assinatura_TV', 'internet_StreamingMovies':'assinatura_Streaming', 'account_Contract': 'tipo_contrato',
       'account_PaperlessBilling': 'fatura_online', 'account_PaymentMethod': 'forma_pagamento',
       'account_Charges.Monthly': 'gasto_mes', 'account_Charges.Total': 'gasto_total'
       })
df

#Coluna de Contas Diárias

df['contas_diarias'] = (df['gasto_mes']/30).round(2)

df['gasto_total'] = pd.to_numeric(df['gasto_total'], errors='coerce')
df['gasto_mes'] = pd.to_numeric(df['gasto_mes'], errors='coerce')
df['contas_diarias'] = pd.to_numeric(df['contas_diarias'], errors='coerce')

df.info()

#media e mediana de gastos e tempo

media_total = df['gasto_total'].mean()
print(f"Média de gasto total: {media_total:.2f}")

media_mensal = df['gasto_mes'].mean()
print(f"Média de gasto mensal: {media_mensal:.2f}")

media_dia = df['contas_diarias'].mean()
print(f"Média de gasto dia: {media_dia:.2f}")

media_contrato = df['meses_contrato'].mean()
print(f"Média de meses de contrato: {media_contrato:.2f}")

mediana_total = df['gasto_total'].median()
mediana_mensal = df['gasto_mes'].median()
mediana_dia = df['contas_diarias'].median()
mediana_contrato = df['meses_contrato'].median()

print(f"Mediana de gasto total: {mediana_total:.2f}")
print(f"Mediana de gasto mensal: {mediana_mensal:.2f}")
print(f"Mediana de gasto dia: {mediana_dia:.2f}")
print(f"Mediana de meses de contrato: {mediana_contrato:.2f}")

#proposção de cancelamento

print(df['Churn'].unique())

df = df[df['Churn'].isin(['Yes', 'No'])]

import matplotlib.pyplot as plt
churn_counts = df['Churn'].value_counts()

plt.figure(figsize=(6, 6))
plt.pie(churn_counts, labels=churn_counts.index, autopct='%1.1f%%', colors=['#66b3ff', '#ff9999'])
plt.title('O cliente cancelou ou não renovou o contrato?')
plt.axis('equal')
plt.show()

#Contagem de Evasão por Variáveis Categóricas

#genero
generos = df['genero'].unique()

for genero in generos:
    dados_genero = df[df['genero'] == genero]['Churn'].value_counts()

    plt.figure(figsize=(5, 5))
    plt.pie(dados_genero, labels=dados_genero.index, autopct='%1.1f%%', startangle=90)
    plt.title(f'Cancelaram do genero: {genero}')
    plt.axis('equal')
    plt.show()

#tipo contrato

import seaborn as sns

sns.countplot(data=df, x='tipo_contrato', hue='Churn', palette='pastel')

plt.title('Evasão de Clientes por Gênero')
plt.xlabel('Tipo de contrato')
plt.ylabel('Quantidade de Clientes')
plt.legend(title='Cancelaram')
plt.show()

#metodo pagamento

sns.countplot(data=df, x='forma_pagamento', hue='Churn')

plt.title('Evasão de Clientes por Gênero')
plt.xlabel('Metodos de pagamento')
plt.ylabel('Quantidade de Clientes')
plt.xticks(rotation=30, ha='right')
plt.legend(title='Cancelaram')
plt.tight_layout()
plt.show()

#Contagem de Evasão por Variáveis Numéricas

#gasto total
plt.figure(figsize=(8, 5))
sns.boxplot(data=df, x='Churn', y='gasto_total')
plt.title('Distribuição do Gasto Total por Churn')
plt.xlabel('Cancelou a Assinatura?')
plt.ylabel('Gasto Total')
plt.show()

#tempo
plt.figure(figsize=(8, 5))
sns.histplot(data=df, x='meses_contrato', hue='Churn', kde=True, element='step', stat='density', common_norm=False)
plt.title('Distribuição do Tempo de Contrato por Churn')
plt.xlabel('Meses de Contrato')
plt.ylabel('Densidade')
plt.show()

#Relatório Final

#Neste projeto, analisei o problema de evasão de clientes (Churn) em uma empresa de telecomunicações para entender quem cancela e por quê.
#Comecei importando os dados e realizando a limpeza necessária.
#Notei que a coluna de evasão continha valores inconsistentes, então padronizei para "Yes" e "No". Também converti colunas numéricas que estavam em formato texto para o tipo correto, além de expandir colunas que continham dados em formato de dicionário para facilitar a análise. Removi ou corrigi valores ausentes para garantir a qualidade dos dados.
#Na análise exploratória, verifiquei que a maioria dos clientes permanece, mas uma parcela significativa cancela. Ao analisar a evasão por gênero, observei que homens e mulheres apresentam proporções semelhantes de cancelamento. Ao explorar variáveis numéricas como gasto total e tempo de contrato, percebi que clientes com contratos mais longos tendem a cancelar menos e que o padrão de gastos também influencia essa decisão. Além disso, identifiquei diferenças importantes em outras variáveis categóricas, como método de pagamento, que ajudam a entender melhor o comportamento dos clientes.
#Concluí que o tempo de contrato é um fator crucial para a retenção, pois clientes mais antigos apresentam menor evasão. Clientes com menor gasto total têm maior probabilidade de cancelar, indicando que o valor percebido pelo cliente é um fator relevante. A distribuição da evasão entre gêneros é equilibrada, o que sugere que estratégias devem considerar ambos os perfis. Também observei que alguns métodos de pagamento e serviços estão associados a maiores índices de cancelamento, o que aponta para áreas onde a empresa pode focar para melhorar a satisfação e retenção.
#Com base nessa análise, recomendo que a empresa invista em programas de fidelização para clientes de longo prazo, além de revisar os planos e pacotes para clientes com menor gasto, visando aumentar o valor percebido. Campanhas personalizadas, baseadas nas características dos clientes, podem ser eficazes para reduzir a evasão. Também é importante monitorar continuamente os métodos de pagamento e serviços relacionados à evasão para agir rapidamente quando necessário.
#Se desejar, posso ajudar a montar esse relatório dentro do notebook, incluindo gráficos e códigos, para deixar tudo organizado e visualmente acessível.